<?php
/* ============================================================================
   TRASH.COM.AU — SERVER PRICING CONFIG
   ----------------------------------------------------------------------------
   Server-side mirror of the pricing half of assets/js/config.js.
   The browser is never trusted with a total; this file is the authority.

   tests/config-parity.py compares the two files and fails if they drift.
   Any price change must be made in BOTH files.
   ========================================================================== */

return [

  // Item prices are ALL-IN. There is no call-out fee. Flat add-ons only,
  // each charged once per booking, never per item.
  'fees' => [
    'stairs' => 100,
    'urgent' => 100,
  ],

  'dismantlingTiers' => [
    'none'  => ['label' => 'None',             'fee' => 0,    'manualReview' => false],
    '1-2'   => ['label' => '1–2 items',        'fee' => 20,   'manualReview' => false],
    '3-5'   => ['label' => '3–5 items',        'fee' => 60,   'manualReview' => false],
    '6plus' => ['label' => '6 or more items',  'fee' => null, 'manualReview' => true],
  ],

  // Any of these routes the booking to manual review. No price is invented.
  'manualReviewConditions' => ['difficultAccess', 'heavyItem'],

  // ** REQUIRED BEFORE LAUNCH ** test values only — must match config.js
  // GENERATED by tools/build-service-area.py — do not hand-edit.
  // 417 postcodes within 150 km of Geelong VIC 3220 (straight line).
  'approvedPostcodes' => [
    '3000','3002','3003','3004','3005','3006','3008','3010','3011','3012',
    '3013','3015','3016','3018','3019','3020','3021','3022','3023','3024',
    '3025','3026','3027','3028','3029','3030','3031','3032','3033','3034',
    '3036','3037','3038','3039','3040','3041','3042','3043','3044','3045',
    '3046','3047','3048','3049','3050','3051','3052','3053','3054','3055',
    '3056','3057','3058','3059','3060','3061','3062','3063','3064','3065',
    '3066','3067','3068','3070','3071','3072','3073','3074','3075','3076',
    '3078','3079','3081','3082','3083','3084','3085','3086','3087','3088',
    '3089','3090','3091','3093','3094','3095','3096','3097','3099','3101',
    '3102','3103','3104','3105','3106','3107','3108','3109','3111','3113',
    '3114','3115','3116','3121','3122','3123','3124','3125','3126','3127',
    '3128','3129','3130','3131','3132','3133','3134','3135','3136','3137',
    '3138','3139','3140','3141','3142','3143','3144','3145','3146','3147',
    '3148','3149','3150','3151','3152','3153','3154','3155','3156','3158',
    '3159','3160','3161','3162','3163','3165','3166','3167','3168','3169',
    '3170','3171','3172','3173','3174','3175','3177','3178','3179','3180',
    '3181','3182','3183','3184','3185','3186','3187','3188','3189','3190',
    '3191','3192','3193','3194','3195','3196','3197','3198','3199','3200',
    '3201','3202','3204','3205','3206','3207','3211','3212','3213','3214',
    '3215','3216','3217','3218','3219','3220','3221','3222','3223','3224',
    '3225','3226','3227','3228','3230','3231','3232','3233','3234','3235',
    '3236','3237','3238','3239','3240','3241','3242','3243','3249','3250',
    '3251','3254','3260','3264','3265','3266','3267','3268','3269','3270',
    '3271','3272','3273','3277','3279','3321','3322','3323','3324','3325',
    '3328','3329','3330','3331','3332','3333','3334','3335','3336','3337',
    '3338','3340','3341','3342','3345','3350','3351','3352','3355','3356',
    '3357','3358','3360','3361','3363','3364','3370','3371','3373','3375',
    '3378','3427','3428','3429','3430','3431','3432','3434','3435','3437',
    '3438','3440','3441','3442','3444','3446','3447','3448','3450','3451',
    '3453','3458','3460','3461','3462','3463','3464','3465','3467','3468',
    '3469','3521','3522','3658','3659','3660','3662','3711','3717','3750',
    '3751','3752','3753','3754','3755','3756','3757','3758','3759','3760',
    '3763','3764','3765','3766','3767','3770','3775','3777','3778','3779',
    '3781','3782','3783','3785','3786','3787','3788','3789','3791','3792',
    '3793','3795','3796','3797','3799','3800','3802','3803','3804','3805',
    '3806','3807','3808','3809','3810','3812','3813','3814','3815','3816',
    '3818','3820','3821','3822','3831','3832','3910','3911','3912','3913',
    '3915','3916','3918','3919','3921','3922','3923','3925','3926','3927',
    '3928','3929','3930','3931','3933','3934','3936','3937','3938','3939',
    '3940','3941','3942','3943','3944','3945','3946','3950','3951','3953',
    '3954','3956','3975','3976','3977','3978','3979','3980','3981','3984',
    '3987','3988','3990','3991','3992','3995','3996',
  ],

  // itemId => [name, charge]. All-in prices; no call-out is added.
  'items' => [
    // Mattresses
    'mat-single-ks'         => ['Mattress — single/king single', 99.00],
    'mat-dqk'               => ['Mattress — double/queen/king', 139.00],
    'mat-cot'               => ['Mattress — cot or crib', 29.00],
    'topper-single-ks'      => ['Topper — single/king single', 19.00],
    'topper-dqk'            => ['Topper — double/queen/king', 29.00],

    // Beds & Bases
    'base-single-ks'        => ['Bed base — single/king single', 79.00],
    'base-dqk'              => ['Bed base — double/queen/king', 99.00],
    'frame-single-ks'       => ['Bed frame — single/king single', 79.00],
    'frame-dqk'             => ['Bed frame — double/queen/king', 99.00],
    'headboard-single-ks'   => ['Headboard — single/king single', 39.00],
    'headboard-dqk'         => ['Headboard — double/queen/king', 49.00],
    'bunk-ss'               => ['Bunk bed — single over single', 129.00],
    'bunk-sd'               => ['Bunk bed — single over double', 169.00],
    'bunk-dd'               => ['Bunk bed — double over double', 229.00],

    // Couches & Sofas
    'sofa-1'                => ['Couch — 1 seat', 69.00],
    'sofa-2'                => ['Couch — 2 seater', 159.00],
    'sofa-3'                => ['Couch — 3 seater', 169.00],
    'sofa-4'                => ['Couch — 4 seater', 189.00],
    'sofa-5'                => ['Couch — 5 seater', 199.00],
    'sofa-6'                => ['Couch — 6 seater', 279.00],
    'sofa-7'                => ['Couch — 7 seater', 299.00],
    'sofa-8'                => ['Couch — 8 seater', 399.00],
    'sofa-chaise'           => ['Chaise section', 59.00],

    // Recliners
    'rec-1'                 => ['Recliner — 1 seat', 79.00],
    'rec-2'                 => ['Recliner — 2 seat', 159.00],
    'rec-3'                 => ['Recliner — 3 seat', 179.00],
    'rec-electric'          => ['Electric recliner', 91.00],   // legacy — needs repricing

    // Sofa Beds & Futons
    'futon-2'               => ['Futon — 2 seater', 169.00],
    'futon-3'               => ['Futon — 3 seater', 199.00],
    'sofabed-1'             => ['Single sofa bed', 97.50],   // legacy — needs repricing
    'sofabed-2'             => ['Two-seater sofa bed', 156.00],   // legacy — needs repricing
    'sofabed-3'             => ['Three-seater sofa bed', 208.00],   // legacy — needs repricing

    // Outdoor Lounges
    'out-1'                 => ['Outdoor couch — armchair', 69.00],
    'out-2'                 => ['Outdoor couch — 2 seater', 149.00],
    'out-3'                 => ['Outdoor couch — 3 seater', 169.00],
    'out-4'                 => ['Outdoor couch — 4 seater', 189.00],
    'out-5'                 => ['Outdoor couch — 5 seater', 199.00],
    'out-6'                 => ['Outdoor couch — 6 seater', 279.00],
    'out-7'                 => ['Outdoor couch — 7 seater', 299.00],
    'out-8'                 => ['Outdoor couch — 8 seater', 399.00],

    // Pianos
    'piano-upright'         => ['Upright piano', 1299.00],
    'piano-baby-grand'      => ['Baby grand piano', 1299.00],
    'piano-grand'           => ['Grand piano', 1299.00],

    // Tyres & Rims
    'rim-tyre-truck'        => ['Rim & tyre — truck', 69.00],
    'rim-tyre-tractor'      => ['Rim & tyre — tractor', 499.00],
    'tyre-truck'            => ['Tyre only — truck', 59.00],
    'rim-car'               => ['Rim only — car', 10.00],
    'rim-truck'             => ['Rim only — truck', 19.00],
    'rim-tractor'           => ['Rim only — tractor', 59.00],

    // Dining Tables
    'table-4'               => ['Four-seat dining table', 39.00],   // legacy — needs repricing
    'table-6'               => ['Six-seat dining table', 52.00],   // legacy — needs repricing
    'table-8'               => ['Eight-seat dining table', 78.00],   // legacy — needs repricing

    // Dining Chairs
    'chair-1'               => ['Individual dining chair', 13.00],   // legacy — needs repricing
    'chair-4'               => ['Set of four dining chairs', 52.00],   // legacy — needs repricing
    'chair-6'               => ['Set of six dining chairs', 78.00],   // legacy — needs repricing

    // Fridges & Freezers
    'fridge-bar'            => ['Bar fridge', 26.00],   // legacy — needs repricing
    'fridge-single'         => ['Standard single-door fridge', 52.00],   // legacy — needs repricing
    'fridge-double'         => ['Large two-door fridge', 84.50],   // legacy — needs repricing
    'fridge-french'         => ['French-door fridge', 97.50],   // legacy — needs repricing
    'freezer-up'            => ['Upright freezer', 52.00],   // legacy — needs repricing
    'freezer-chest'         => ['Chest freezer', 65.00],   // legacy — needs repricing
  ],

  'maxQuantityPerItem' => 20,

  /* Optional photo attachments. Nothing about pricing depends on these. */
  'maxPhotos'             => 6,
  'maxPhotoBytes'         => 3 * 1024 * 1024,    // per photo, after browser resize
  'maxPhotoPayloadBytes'  => 24 * 1024 * 1024,   // whole request


  /* Where submitted bookings and photos are written. Keep BOTH outside the
     webroot — an uploaded file under the webroot is a served file.
     ** REQUIRED BEFORE LAUNCH ** point these at real paths on the server. */
  'bookingStorePath' => __DIR__ . '/../../trash-bookings',
  'photoStorePath'   => __DIR__ . '/../../trash-photos',
];
